CREATE TABLE USERS (
    username VARCHAR2(50) PRIMARY KEY,
    fullname VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(256) NOT NULL,
    type INTEGER NOT NULL
);

CREATE TABLE REQUESTS (
    requestid INTEGER PRIMARY KEY,
    owner VARCHAR2(50) NOT NULL,
    time INTEGER NOT NULL,
    type INTEGER NOT NULL,
    amt INTEGER NOT NULL,
    acceptedPickUp INTEGER NOT NULL,
    acceptedDropOff INTEGER NOT NULL,
    CONSTRAINT request_owner 
        FOREIGN KEY (owner) REFERENCES USERS(USERNAME) ON DELETE CASCADE ON UPDATE CASCADE
);